import requests
CITY_COUNTIES = {
    'Atlanta': 'Fulton',
    'Savannah': 'Chatham',
    'Augusta': 'Richmond',
    'Columbus': 'Muscogee',
    'St. Simons': 'Glynn',
    'Macon': 'Bibb',
    'Albany': 'Dougherty',
    'Athens': 'Clarke',
    'Roswell': 'Fulton'
}
import requests

def get_nws_alert_level(city_name):
    # returns nummerical severeness (0-1.0 scale) of severity of alert 
    county = CITY_COUNTIES.get(city_name, '')
    
    try:
        response = requests.get(
            "https://api.weather.gov/alerts/active?area=GA", #api with live updates
            timeout=5,
            headers={"User-Agent": "CrisisMap/1.0"}  # NWS requires a User-Agent
        )
        data = response.json()
    except Exception:
        return 0.0  # API down, return safe fallback, also sometimes no risk 

    best_score = 0.0
    
    for feature in data.get("features", []):
        props = feature.get("properties", {})
        event = props.get("event", "")
        area  = props.get("areaDesc", "")
        
        # Check if this alert covers our city's county
        if county.lower() not in area.lower():
            continue
        
        # Score the alert type
        if "Flood Warning" in event or "Flash Flood Emergency" in event:
            best_score = max(best_score, 1.0)
        elif "Flood Watch" in event or "Flash Flood Watch" in event:
            best_score = max(best_score, 0.67)
        elif "Flood Advisory" in event:
            best_score = max(best_score, 0.33)
    
    return best_score #if no risk / another warning then just returns 0 

import requests

def get_gauge_ratio(city_name):
    # Map cities to nearby USGS gauge station IDs
    # IDs generated by perplexity based on source 
    GAUGE_STATIONS = {
    'Atlanta': '02336000',     # Chattahoochee River at Atlanta, GA [web:25]
    'Savannah': '021989773',   # Savannah River at USACE Dock, at Savannah, GA [web:21]
    'Augusta': '02197000',     # Savannah River at Augusta, GA [web:26]
    'Columbus': '02341460',    # Chattahoochee River at 14th St, at Columbus, GA [web:23]
    'St. Simons': '03085700',  # Brunswick River at St. Simons, GA (nearby coastal gauge)
    'Macon': '02213000',       # Ocmulgee River at Macon, GA [web:29]
    'Albany': '02359500',      # Flint River at Albany, GA
    'Athens': '02217500',      # Middle Oconee River at Athens, GA
    'Roswell': '02329900'      # Big Creek near Roswell, GA (Chattahoochee tributary)
}

    station_id = GAUGE_STATIONS.get(city_name)
    url = f"https://waterservices.usgs.gov/nwis/iv/?sites={station_id}&parameterCd=00065&format=json"
    
    response = requests.get(url, timeout=5)
    data = response.json()
    
    # Dig into the JSON to get current height
    current_height = float(data['value']['timeSeries'][0]['values'][0]['value'][0]['value'])
    flood_stage = 25.0   # hardcode per city for now
    
    return min(current_height / flood_stage, 1.0)